// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALStRsbO42Lj-YL5N94O1asyB6BO1_slw',
    appId: '1:23944663766:web:fb2da33d7a7b6ec7166f77',
    messagingSenderId: '23944663766',
    projectId: 'aprob-97efe',
    authDomain: 'aprob-97efe.firebaseapp.com',
    storageBucket: 'aprob-97efe.appspot.com',
    measurementId: 'G-R36VZ4XT2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALStRsbO42Lj-YL5N94O1asyB6BO1_slw',
    appId: '1:667895340494:android:466045b0f31fd3818ddf9f',
    messagingSenderId: '23944663766',
    projectId: 'pe-fesa-aproboc-fb-dev01',
    storageBucket: 'pe-fesa-aproboc-fb-dev01.appspot.com',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVt2zZUQvcRFXbubP90GCN3DbMzcdxMPU',
    appId: '1:23944663766:ios:4f0078b79e27142e166f77',
    messagingSenderId: '23944663766',
    projectId: 'aprob-97efe',
    storageBucket: 'aprob-97efe.appspot.com',
    iosClientId:
        '23944663766-92rfomi369h3337lgvsqvfbgqguvpr85.apps.googleusercontent.com',
    iosBundleId: 'com.example.ordencompra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVt2zZUQvcRFXbubP90GCN3DbMzcdxMPU',
    appId: '1:23944663766:ios:4f0078b79e27142e166f77',
    messagingSenderId: '23944663766',
    projectId: 'aprob-97efe',
    storageBucket: 'aprob-97efe.appspot.com',
    iosClientId:
        '23944663766-92rfomi369h3337lgvsqvfbgqguvpr85.apps.googleusercontent.com',
    iosBundleId: 'com.example.ordencompra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaOJzI9P8fduhpZXpzNO95U9fLIN4vEuo',
    appId: '1:23944663766:web:76921fca8b426513166f77',
    messagingSenderId: '23944663766',
    projectId: 'aprob-97efe',
    authDomain: 'aprob-97efe.firebaseapp.com',
    storageBucket: 'aprob-97efe.appspot.com',
    measurementId: 'G-L8TRZG3C7H',
  );
}
